- hosts: k8s-cluster
  tasks:
    - set_fact:
        kubeconfig_localhost: true
        artifacts_dir: "{{ inventory_dir }}"
      when: not offline

- name: 'Bringing kubeconfig.dec in place'
  hosts: k8s-cluster
  become: no
  tasks:
    - delegate_to: localhost
      when: not offline
      block:
      - name: "Checking if 'admin.conf' file still exists"
        stat:
          path: "{{ artifacts_dir }}/admin.conf"
        register: file_adminconf
      - when: file_adminconf.stat.exists
        block:
        - name: 'Renaming kubeconfig file provided by Kubespray'
          copy:
            src: "{{ artifacts_dir }}/admin.conf"
            dest: "{{ artifacts_dir }}/../kubeconfig.dec"
        - file:
            path: "{{ artifacts_dir }}/admin.conf"
            state: absent

- hosts: etcd
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - etcd-helpers

- import_playbook: roles-external/kubespray/cluster.yml

- hosts: k8s-cluster
  tasks:
    - name: Annotate nodes
      command: "kubectl annotate node --overwrite {{ inventory_hostname }} {{ item.key }}={{ item.value }}"
      with_dict: "{{ node_annotations | default({}) }}"

- import_playbook: kubernetes_logging.yml
